sudo: false
dist: xenial

language: python

cache:
  directories:
    - ~/.cache/pip

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install coveralls
  - pip install -e .\[dev\]

script:
  - pytest tests --cov click_plugins --cov-report term-missing

after_success:
  - coveralls
